### ISSUE TITLE
No nagmq sockets on icinga reload

### ISSUE THREAD

**Issue by gitshaw** [jbreams/nagmq#22]
i am using nagmq broker with icinga but having a problem with nagmq sockets when issuing icinga reload. 

no sockets are recreated if i issue reload:
![nagmq_no_sockets](https://f.cloud.github.com/assets/1745979/2269559/d6e591a2-9edb-11e3-9318-f4eca4f98ea3.jpg)

if i do icinga restart then everything works as expected: 
![nagmq_sockets](https://f.cloud.github.com/assets/1745979/2269567/04c07114-9edc-11e3-82c1-88ec5eb56560.jpg)

Nothing present in the icinga.debug log - loading and unloading of the module seems fine.

Reason = 1 (restart)
Reason = 2 (reload)

![nagmq](https://f.cloud.github.com/assets/1745979/2269570/1c0e11c8-9edc-11e3-9713-c38011dcf0fd.jpg)

Any one else had this problem with nagios/icinga. 

thanks.

**Comment by thardie** [comment]
I've run into the same problem building a similar plugin. I've traced it down to the fact that Nagios (I'm running 4.0.7) forks the command file worker process after calling plugins. The file worker process inherits the file handles opened in your plugin, and when nagios is reloaded, that process is not restarted, so when your plugin "closes" the zmq socket, the file worker process still holds it. The main nagios restart loop needs to be changed to stop the file worker process during a reload, and this should fix this issue.

**Comment by thardie** [comment]
I added a shutdown_command_file_worker() call into my plugin deinit, and it solved my issue.

**Comment by jbreams** [comment]
This should be resolved in https://github.com/jbreams/nagmq/commit/4245c170f23b0a6be1847bceb62e43ee20c5614d
