### ISSUE TITLE
Error during make. 

### ISSUE THREAD

**Issue by jlombardo29** [jbreams/nagmq#31]
[root@box nagmq]# make
Making all in mods
make[1]: Entering directory `/opt/nagmq/mods'
make  all-am
make[2]: Entering directory `/opt/nagmq/mods'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../dnxmq    -I/opt/nagios-4.2.0/include -I/opt/nagios-4.2.0 -I/usr/local/include   -I/usr/local/include    -Werror=implicit-function-declaration -g -O2 -MT nagmq_la-nagmq_req.lo -MD -MP -MF .deps/nagmq_la-nagmq_req.Tpo -c -o nagmq_la-nagmq_req.lo `test -f 'nagmq_req.c' || echo './'`nagmq_req.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../dnxmq -I/opt/nagios-4.2.0/include -I/opt/nagios-4.2.0 -I/usr/local/include -I/usr/local/include -Werror=implicit-function-declaration -g -O2 -MT nagmq_la-nagmq_req.lo -MD -MP -MF .deps/nagmq_la-nagmq_req.Tpo -c nagmq_req.c  -fPIC -DPIC -o .libs/nagmq_la-nagmq_req.o
nagmq_req.c:875: error: expected ‘)’ before ‘*’ token
nagmq_req.c:924: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
nagmq_req.c: In function ‘do_list_comments’:
nagmq_req.c:933: error: ‘comment’ undeclared (first use in this function)
nagmq_req.c:933: error: (Each undeclared identifier is reported only once
nagmq_req.c:933: error: for each function it appears in.)
nagmq_req.c:933: error: ‘clck’ undeclared (first use in this function)
nagmq_req.c:951: error: implicit declaration of function ‘parse_comment’
make[2]: *** [nagmq_la-nagmq_req.lo] Error 1
make[2]: Leaving directory `/opt/nagmq/mods'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/nagmq/mods'
make: *** [all-recursive] Error 1
[root@box nagmq]# 

Nagios 4.2.0

**Comment by jbreams** [comment]
Looks like 4.2 was just released. Nagios is pretty terrible at maintaining an API I'll check to see what changed in their API and push a fix.

**Comment by jbreams** [comment]
I think this is fixed in a8539ce737250a716ab5297a16e402d450bb1979, can you check and close?

**Comment by jlombardo29** [comment]
Sure. will update soon.
