### ISSUE TITLE
enabling the broker module causes SIGSEGV

### ISSUE THREAD

**Issue by jlombardo29** [jbreams/nagmq#32]
RHEL 6.8
Nagios 4.2.0
selinux permissive

When I have the broker module enabled in the nagios.cfg  nagios dies with a SIGSEGV in about a minute after starting.  

an strace -f  doesn't give much insight.  
I'm wondering if you could take a stab at what might be causing it.

**Comment by jbreams** [comment]
Sure. Do you have a stack trace or a core dump or something I could look at?

**Comment by jlombardo29** [comment]
strace sent. 

> nagios[8222]: segfault at 0 ip 00007fcc89be2508 sp 00007ffd01a3a6f8 error 4 in libc-2.12.so[7fcc89aba000+18a000]
nagios[8847]: segfault at 0 ip 00007f283bcae508 sp 00007ffd30d111e8 error 4 in libc-2.12.so[7f283bb86000+18a000]
nagios[10486]: segfault at 0 ip 00007f448ebf8508 sp 00007ffd3e138608 error 4 in libc-2.12.so[7f448ead0000+18a000]

from dmesg

**Comment by jlombardo29** [comment]
Resolved with latest push.

Thanks again.

**Comment by jbreams** [comment]
Diagnosed offline, and resolved in e7929a97f6528e541cc57563b62ed77d78476050.
